export const depOptions = [
    { value:"ASDN: Arts and Science, Office of the Dean", label: "ASDN: Arts and Science, Office of the Dean" },
    { value:"Anatomy and Cell Biology", label: "Anatomy and Cell Biology" },
    { value:"Anthropology", label: "Anthropology" },
    { value:"Anthropology (UTSC)", label: "Anthropology (UTSC)" },
    { value:"Art History", label: "Art History" },
    { value:"Astronomy and Astrophysics", label: "Astronomy and Astrophysics" },
    { value:"Biochemistry", label: "Biochemistry" },
    { value:"Biological Sciences (UTSC)", label: "Biological Sciences (UTSC)" },
    { value:"Biology", label: "Biology" },
    { value:"Canadian Institute for Theoretical Astrophysics", label: "Canadian Institute for Theoretical Astrophysics" },
    { value:"Cell and Systems Biology", label: "Cell and Systems Biology" },
    { value:"Centre for Criminology and Sociolegal Studies", label: "Centre for Criminology and Sociolegal Studies" },
    { value:"Centre for Critical Development Studies (UTSC)", label: "Centre for Critical Development Studies (UTSC)" },
    { value:"Centre for Diaspora & Transnational Studies", label: "Centre for Diaspora & Transnational Studies" },
    { value:"Centre for Drama, Theatre and Performance Studies", label: "Centre for Drama, Theatre and Performance Studies" },
    { value:"Centre for European, Russian and Eurasian Studies", label: "Centre for European, Russian and Eurasian Studies" },
    { value:"Centre for Industrial Relations and Human Resources", label: "Centre for Industrial Relations and Human Resources" },
    { value:"Centre for Study of United States", label: "Centre for Study of United States" },
    { value:"Centre for Teaching and Learning (UTSC)", label: "Centre for Teaching and Learning (UTSC)" },
    { value:"Chemical Engineering and Applied Chemistry", label: "Chemical Engineering and Applied Chemistry" },
    { value:"Chemical and Physical Sciences", label: "Chemical and Physical Sciences" },
    { value:"Chemistry", label: "Chemistry" },
    { value:"Cinema Studies Institute", label: "Cinema Studies Institute" },
    { value:"Civil and Mineral Engineering", label: "Civil and Mineral Engineering" },
    { value:"Classics", label: "Classics" },
    { value:"Computer Science", label: "Computer Science" },
    { value:"Cross Disciplinary Programs Office", label: "Cross Disciplinary Programs Office" },
    { value:"Department for the Study of Religion", label: "Department for the Study of Religion" },
    { value:"Dept. of Arts, Culture & Media (UTSC)", label: "Dept. of Arts, Culture & Media (UTSC)" },
    { value:"Dept. of Computer & Mathematical Sci (UTSC)", label: "Dept. of Computer & Mathematical Sci (UTSC)" },
    { value:"Dept. of Historical & Cultural Studies (UTSC)", label: "Dept. of Historical & Cultural Studies (UTSC)" },
    { value:"Dept. of Physical & Environmental Sci (UTSC)", label: "Dept. of Physical & Environmental Sci (UTSC)" },
    { value:"Division of Engineering Science", label: "Division of Engineering Science" },
    { value:"Earth Sciences", label: "Earth Sciences" },
    { value:"East Asian Studies", label: "East Asian Studies" },
    { value:"Ecology and Evolutionary Biology", label: "Ecology and Evolutionary Biology" },
    { value:"Economics", label: "Economics" },
    { value:"Edward S. Rogers Sr. Dept. of Electrical & Computer Engin.", label: "Edward S. Rogers Sr. Dept. of Electrical & Computer Engin." },
    { value:"Engineering First Year Office", label: "Engineering First Year Office" },
    { value:"English", label: "English" },
    { value:"English (UTSC)", label: "English (UTSC)" },
    { value:"English and Drama", label: "English and Drama" },
    { value:"Factor Inwentash Faculty of Social Work", label: "Factor Inwentash Faculty of Social Work" },
    { value:"Faculty of Applied Science & Engineering", label: "Faculty of Applied Science & Engineering" },
    { value:"Faculty of Arts and Science", label: "Faculty of Arts and Science" },
    { value:"Faculty of Music", label: "Faculty of Music" },
    { value:"French", label: "French" },
    { value:"Geography and Planning", label: "Geography and Planning" },
    { value:"Geography, Geomatics and Environment", label: "Geography, Geomatics and Environment" },
    { value:"Germanic Languages & Literatures", label: "Germanic Languages & Literatures" },
    { value:"Health and Society (UTSC)", label: "Health and Society (UTSC)" },
    { value:"Historical Studies", label: "Historical Studies" },
    { value:"History", label: "History" },
    { value:"Human Biology Program", label: "Human Biology Program" },
    { value:"Human Geography (UTSC)", label: "Human Geography (UTSC)" },
    { value:"Immunology", label: "Immunology" },
    { value:"Indigenous Studies Arts & Science", label: "Indigenous Studies Arts & Science" },
    { value:"Inst for Studies in Transdisciplinary Engin Educ & Practice", label: "Inst for Studies in Transdisciplinary Engin Educ & Practice" },
    { value:"Inst. for the History & Philosophy of Science & Technology", label: "Inst. for the History & Philosophy of Science & Technology" },
    { value:"Institute for Management and Innovation", label: "Institute for Management and Innovation" },
    { value:"Institute for the Study of University Pedagogy", label: "Institute for the Study of University Pedagogy" },
    { value:"Institute of Biomedical Engineering", label: "Institute of Biomedical Engineering" },
    { value:"Institute of Communication and Culture", label: "Institute of Communication and Culture" },
    { value:"Italian Studies", label: "Italian Studies" },
    { value:"Jewish Studies", label: "Jewish Studies" },
    { value:"John H. Daniels Faculty of Architecture, Landscape, & Design", label: "John H. Daniels Faculty of Architecture, Landscape, & Design" },
    { value:"Laboratory Medicine and Pathobiology", label: "Laboratory Medicine and Pathobiology" },
    { value:"Language Studies", label: "Language Studies" },
    { value:"Language Studies (UTSC)", label: "Language Studies (UTSC)" },
    { value:"Linguistics", label: "Linguistics" },
    { value:"Management", label: "Management" },
    { value:"Management (UTSC)", label: "Management (UTSC)" },
    { value:"Materials Science and Engineering", label: "Materials Science and Engineering" },
    { value:"Mathematical and Computational Sciences", label: "Mathematical and Computational Sciences" },
    { value:"Mathematics", label: "Mathematics" },
    { value:"Mechanical & Industrial Engineering", label: "Mechanical & Industrial Engineering" },
    { value:"Molecular Genetics", label: "Molecular Genetics" },
    { value:"Munk School of Global Affairs and Public Policy", label: "Munk School of Global Affairs and Public Policy" },
    { value:"Near & Middle Eastern Civilizations", label: "Near & Middle Eastern Civilizations" },
    { value:"New College", label: "New College" },
    { value:"Nutritional Sciences", label: "Nutritional Sciences" },
    { value:"Pharmacology", label: "Pharmacology" },
    { value:"Philosophy", label: "Philosophy" },
    { value:"Philosophy (UTSC)", label: "Philosophy (UTSC)" },
    { value:"Physics", label: "Physics" },
    { value:"Physiology", label: "Physiology" },
    { value:"Political Science", label: "Political Science" },
    { value:"Political Science (UTSC)", label: "Political Science (UTSC)" },
    { value:"Psychology", label: "Psychology" },
    { value:"Psychology (UTSC)", label: "Psychology (UTSC)" },
    { value:"Rotman Commerce", label: "Rotman Commerce" },
    { value:"School of Environment", label: "School of Environment" },
    { value:"Sexual Diversity Studies", label: "Sexual Diversity Studies" },
    { value:"Slavic Languages and Literatures", label: "Slavic Languages and Literatures" },
    { value:"Sociology", label: "Sociology" },
    { value:"Sociology (UTSC)", label: "Sociology (UTSC)" },
    { value:"Spanish and Portuguese", label: "Spanish and Portuguese" },
    { value:"St. Michael's College", label: "St. Michael's College" },
    { value:"Statistical Sciences", label: "Statistical Sciences" },
    { value:"Trinity College", label: "Trinity College" },
    { value:"University College", label: "University College" },
    { value:"University of Toronto Mississauga", label: "University of Toronto Mississauga" },
    { value:"University of Toronto Scarborough", label: "University of Toronto Scarborough" },
    { value:"Victoria College", label: "Victoria College" },
    { value:"Visual Studies", label: "Visual Studies" },
    { value:"Women and Gender Studies Institute", label: "Women and Gender Studies Institute" }
];